"""Historical import facade for the neutral source-evidence helpers."""

from evidence_core import (
    CURRENT_QUOTE_LENGTH_POLICY,
    END_MARKER,
    EVIDENCE_POLICY_VERSION,
    LEGACY_FIXTURE_QUOTE_LENGTH_POLICY,
    NON_STATISTICAL_MIN_WORDS,
    START_MARKER,
    STATISTICAL_MARKERS,
    STATISTICAL_MIN_WORDS,
    TRUNCATED_END_MARKER,
    UNTRUSTED_SOURCE_INSTRUCTION_POLICY,
    UNTRUSTED_SOURCE_LABEL,
    ParsedQuoteBlock,
    PostExtractionFilterResult,
    QuoteLengthPolicy,
    QuoteMetrics,
    UntrustedSourceText,
    assemble_quote_block_from_selected_segments,
    build_source_snapshot,
    count_claim_keyword_matches,
    filter_provisional_candidate,
    find_segment_offsets,
    has_statistical_markers,
    numbered_source_text,
    parse_extracted_quote_block,
    selected_segments_from_selection,
    validate_bracket_context,
    validate_quote_substance,
    validate_snapshot_integrity,
    verify_candidate_against_snapshot,
)
from utils import derive_quote_block_id

__all__ = [
    "CURRENT_QUOTE_LENGTH_POLICY",
    "END_MARKER",
    "EVIDENCE_POLICY_VERSION",
    "LEGACY_FIXTURE_QUOTE_LENGTH_POLICY",
    "NON_STATISTICAL_MIN_WORDS",
    "ParsedQuoteBlock",
    "PostExtractionFilterResult",
    "QuoteLengthPolicy",
    "QuoteMetrics",
    "START_MARKER",
    "STATISTICAL_MARKERS",
    "STATISTICAL_MIN_WORDS",
    "TRUNCATED_END_MARKER",
    "UNTRUSTED_SOURCE_INSTRUCTION_POLICY",
    "UNTRUSTED_SOURCE_LABEL",
    "UntrustedSourceText",
    "assemble_quote_block_from_selected_segments",
    "build_source_snapshot",
    "count_claim_keyword_matches",
    "derive_quote_block_id",
    "filter_provisional_candidate",
    "find_segment_offsets",
    "has_statistical_markers",
    "numbered_source_text",
    "parse_extracted_quote_block",
    "selected_segments_from_selection",
    "validate_bracket_context",
    "validate_quote_substance",
    "validate_snapshot_integrity",
    "verify_candidate_against_snapshot",
]
